// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnawJtwRBwYITLMsH3Dg7rKbINV43uoiI',
    appId: '1:404967972995:web:a6c4b352e52f84c6ec7bb6',
    messagingSenderId: '404967972995',
    projectId: 'fir-projects-f47db',
    authDomain: 'fir-projects-f47db.firebaseapp.com',
    storageBucket: 'fir-projects-f47db.appspot.com',
    measurementId: 'G-GTYKWYK9BB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtyhMEVusYfXZdy0ReQX5kUr2USGXuKFc',
    appId: '1:404967972995:android:6a3b7b41dfe88c70ec7bb6',
    messagingSenderId: '404967972995',
    projectId: 'fir-projects-f47db',
    storageBucket: 'fir-projects-f47db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACnFLF7BhIcWOLxeITxAh3Q6n-OVLAWSI',
    appId: '1:404967972995:ios:9d0a7e5c2488e5d7ec7bb6',
    messagingSenderId: '404967972995',
    projectId: 'fir-projects-f47db',
    storageBucket: 'fir-projects-f47db.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

}