// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxXCrMwx7VnSP_F1q6yDgX2TdjVP8S92I',
    appId: '1:336322308828:web:7d75379e940841ddb26219',
    messagingSenderId: '336322308828',
    projectId: 'fir-practice1-6c4bc',
    authDomain: 'fir-practice1-6c4bc.firebaseapp.com',
    storageBucket: 'fir-practice1-6c4bc.appspot.com',
    measurementId: 'G-THT573FEFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANifv2rhHIbkrpSjEmEjND2TPfQWbCSGo',
    appId: '1:336322308828:android:5caffb1d1b2aaa93b26219',
    messagingSenderId: '336322308828',
    projectId: 'fir-practice1-6c4bc',
    storageBucket: 'fir-practice1-6c4bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCR9wk49LP3sLul1M42KhrCvJDng5hD98',
    appId: '1:336322308828:ios:d212d332edce5c96b26219',
    messagingSenderId: '336322308828',
    projectId: 'fir-practice1-6c4bc',
    storageBucket: 'fir-practice1-6c4bc.appspot.com',
    iosBundleId: 'com.example.firebasePractice1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCR9wk49LP3sLul1M42KhrCvJDng5hD98',
    appId: '1:336322308828:ios:d212d332edce5c96b26219',
    messagingSenderId: '336322308828',
    projectId: 'fir-practice1-6c4bc',
    storageBucket: 'fir-practice1-6c4bc.appspot.com',
    iosBundleId: 'com.example.firebasePractice1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxXCrMwx7VnSP_F1q6yDgX2TdjVP8S92I',
    appId: '1:336322308828:web:5a9369a7b1f05c0ab26219',
    messagingSenderId: '336322308828',
    projectId: 'fir-practice1-6c4bc',
    authDomain: 'fir-practice1-6c4bc.firebaseapp.com',
    storageBucket: 'fir-practice1-6c4bc.appspot.com',
    measurementId: 'G-5ZW1H48T9G',
  );
}
