// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHDM7ZhXtY05dIMKpzRBPY9EId73hbDpY',
    appId: '1:461440928543:web:1579d246abc6bad2e4fe2a',
    messagingSenderId: '461440928543',
    projectId: 'fir-project2-980ac',
    authDomain: 'fir-project2-980ac.firebaseapp.com',
    storageBucket: 'fir-project2-980ac.appspot.com',
    measurementId: 'G-VZDSC053WF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYb7EvSoiB5DLCbbzOxiDlytZUx1FKdfs',
    appId: '1:461440928543:android:64a8d6a7d8e08c18e4fe2a',
    messagingSenderId: '461440928543',
    projectId: 'fir-project2-980ac',
    storageBucket: 'fir-project2-980ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJp5mOuXf8JnB8N4QxKk1eFIW12psxWqI',
    appId: '1:461440928543:ios:184330b4f349e17fe4fe2a',
    messagingSenderId: '461440928543',
    projectId: 'fir-project2-980ac',
    storageBucket: 'fir-project2-980ac.appspot.com',
    iosBundleId: 'com.example.firebasePractice2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJp5mOuXf8JnB8N4QxKk1eFIW12psxWqI',
    appId: '1:461440928543:ios:184330b4f349e17fe4fe2a',
    messagingSenderId: '461440928543',
    projectId: 'fir-project2-980ac',
    storageBucket: 'fir-project2-980ac.appspot.com',
    iosBundleId: 'com.example.firebasePractice2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHDM7ZhXtY05dIMKpzRBPY9EId73hbDpY',
    appId: '1:461440928543:web:1a87c81b248a032be4fe2a',
    messagingSenderId: '461440928543',
    projectId: 'fir-project2-980ac',
    authDomain: 'fir-project2-980ac.firebaseapp.com',
    storageBucket: 'fir-project2-980ac.appspot.com',
    measurementId: 'G-M7B9SVW14Y',
  );
}
